export const SERVICE_DEFINITION_GET_ALL = 'SERVICE_DEFINITION_GET_ALL';
export const SERVICE_DEFINITION_GET_ALL_SUCCESS = 'SERVICE_DEFINITION_GET_ALL_SUCCESS';
export const SERVICE_DEFINITION_GET_ALL_ERROR = 'SERVICE_DEFINITION_GET_ALL_ERROR';

export const SERVICE_INSTANCE_GET_ALL = 'SERVICE_INSTANCE_GET_ALL';
export const SERVICE_INSTANCE_GET_ALL_SUCCESS = 'SERVICE_INSTANCE_GET_ALL_SUCCESS';
export const SERVICE_INSTANCE_GET_ALL_ERROR = 'SERVICE_INSTANCE_GET_ALL_ERROR';